### ISSUE TITLE
Look for help: encountering a problem when running reproduce.py

### ISSUE THREAD

**Issue by L-fu-des22** [grimmlab/gumbeldore#1]
Dear authors:
         When I run your code reproduce.py, I encounter a problem. When it comes to the part of solving cvrp, there is no result for a long time, while the code for solving TSP can run normally. Could you give me some suggestions to solve this problem? Thank you very much!

**Comment by johnnycrab** [comment]
Hey,
Thanks for reaching out! It could be something similar to what is mentioned in the Readme: In `core.GumbeldorDataset`, tqdm is used for the progress bar. However, as `ray.get` is called on the workers after all data has been collected, the program will stall without throwing an error if an error occurs in one of the workers. That would be my first guess, so to "unsilence" errors in the workers, place a `ray.get` after the future tasks have been created and before tqdm in `core/gumbeldore_dataset.py` as follows (where the "+" line is):

```python
# Kick off workers
  future_tasks = [
      async_sbs_worker.remote(
          self.config, job_pool, network_weights, device,
          batch_size_gpu if device != "cpu" else batch_size_cpu,
          self.beam_leaves_to_result_fn,
          self.get_network_fn, self.trajectory_cls,
          cpu_cores[i], memory_aggressive
      )
      for i, device in enumerate(self.devices_for_workers)
  ]
+ ray.get(future_tasks)  # PLACE THIS LINE HERE
  with tqdm(total=len(problem_instances)) as progress_bar:
      while None in results:
```

Let me know if this helps and you get more information on the problem! Also, let me know if I can assist further.

Best,
Jonathan

**Comment by L-fu-des22** [comment]
Thank you very much for your prompt reply. Your suggestion is effective. I found that the error was caused by torch.concatenate() in cvrp/bq_network.py, which may be a problem with the torch version. I changed it to torch.cat() and it works normally. Thank you again for your help!
